/**/**:
  ros__parameters:
    rate: # Hz
      external_loop_control: 100.0 
      internal_loop_control: 250.0 
      diagnostics: 100.0

    takeoff:
      height: 1.5 # m
      speed: 1.0 # m/s

    land:
      increment_rampdown: 0.15 # [0, 1]
      threshold_detect: 0.70 # [0, 1]
      height_threshold: 0.5 # m
      speed: 0.3 # m/s

    filter_params:
      butterworth:
        gyro_a: [1.0000, -1.5782, 0.6528]
        gyro_b: [0.018650, 0.037301, 0.018650]

        motor_a: [1.0000, -1.5782, 0.6528]
        motor_b: [0.018650, 0.037301, 0.018650]

    safe_area:
      enabled: false

      # This is the range of the safety area in x, y and z axis
      constraints:
        x: [-2.0, 2.0] 
        y: [-2.0, 2.0]
        z: [0.5, 3.0]

        # The cube down represent up constraints
        #  (x , y)
        # (2.0, 2.0)  --------------------- (2.0, -2.0)
        #     |                                  | 
        #     |                                  | 
        #     |                                  | 
        #     |                                  | 
        #     |                                  |       0.5 <= z <= 3.0
        #     |                                  | 
        #     |                                  | 
        #     |                                  | 
        #     |                                  | 
        # (-2.0, 2.0) --------------------- (-2.0, -2.0)

